defaults:
  - model: mamba
  - data: midi
  - _self_


training:
  num_workers: 4 # lower this setting in case of workers segmentation fault error
  batch_size: 1
  epochs: 60
  learning_rate: 1e-4
  step_size: 3
  gamma: 0.1
  callbacks:
    patience: 5


wandb:
  project: "WIMU mamba-music-generation"
  entity: "wut-zzsn"
  group: "sequence"
  cleanup:
    dry_run: False
    run_cleanup_every_epochs: 5

models:
  save_path: models

inference:
  wandb_model_full_name: "" # example: "wut-zzsn/WIMU mamba-music-generation/model-mn6cowxw:v4"
  model_path: "" # optional, if you want to load model that is not in wandb fill this and leave wandb_model_full_name empty
  input_length: 1   # Example length
  input_ids: [1]
  max_length: 1024
  temperature: 0.8
  top_k: 70
  repetition_penalty: 0.9
  overtrained_song: []