defaults:
  - process: process1
  - model: mamba
  - _self_

data:
  path: data
  dataset_name: maestro
  tokenizer: remi
  train_split: 0.8

training:
  num_workers: 4 # lower this setting in case of workers segmentation fault error
  batch_size: 4
  epochs: 10
  learning_rate: 1e-3
  step_size: 3
  gamma: 0.1
  callbacks:
    patience: 10

wandb:
  project: "WIMU mamba-music-generation"

models:
  save_path: models

inference:
  wandb_run_id: "skilled-dream-13_model.pt"
  model_path: "models/skilled-dream-13_model.pt" # optional, if you want to load model that is not in wandb fill this and leave wandb_run_id empty
